name: MyAI
channels:
  - defaults
  - conda-forge
dependencies:
  - fastapi=0.85.1
  - celery=5.2.3
  - pydantic=1.10.5
  - uvicorn=0.19.0
  - psycopg2=2.9.3
  - pika=1.2.0
  - pip
  - pip:
      - langchain==0.0.126
      - pinecone-client==2.0.1